# Generated by Django 3.2.6 on 2021-09-02 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20210826_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='conmment_count',
        ),
        migrations.AddField(
            model_name='boards',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
