# Generated by Django 3.2.6 on 2021-09-14 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_rename_parent_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='boards',
            table='Board',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.boards')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
