# Generated by Django 3.2.6 on 2021-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210914_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='reply',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterModelTable(
            name='boards',
            table=None,
        ),
    ]
