# Generated by Django 3.2.6 on 2021-09-18 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_auto_20210917_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='voter',
            field=models.ManyToManyField(related_name='voter_board', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boards',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_board', to=settings.AUTH_USER_MODEL),
        ),
    ]
