# Generated by Django 3.2.6 on 2021-11-05 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20211029_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='category',
            field=models.ForeignKey(default='자유', on_delete=django.db.models.deletion.CASCADE, to='base.category'),
            preserve_default=False,
        ),
    ]
