# Generated by Django 3.2.6 on 2021-11-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_boards_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
    ]
