# Generated by Django 3.2.6 on 2021-11-14 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_auto_20211109_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='voter',
            field=models.ManyToManyField(blank=True, related_name='voter_board', to=settings.AUTH_USER_MODEL),
        ),
    ]
